import dotenv from 'dotenv';
dotenv.config();

import { sequelize } from './config/db.js';
import Car from './models/Car.js';
import GalleryItem from './models/Gallery.js';
import Testimonial from './models/Testimonial.js';
import SpecialOffer from './models/SpecialOffer.js';
import Admin from './models/Admin.js';

const PORT = process.env.PORT || 5000;
const BASE_URL = `http://localhost:${PORT}/uploads/cars`;
const CLIENTS_BASE_URL = `http://localhost:${PORT}/uploads/clients`;

const cars = [
  {
    name: 'Audi A4 Premium',
    brand: 'Audi',
    year: 2022,
    price: 3250000,
    mileage: 15400,
    fuel: 'Petrol',
    transmission: 'Automatic',
    type: 'Sedan',
    state: 'Punjab',
    city: 'Chandigarh',
    image: `${BASE_URL}/Audi A4 Premium.webp`,
    featured: false,
    badge: 'Luxury',
    color: 'Black',
    engine: '2.0L TFSI Turbo',
    seats: 5,
    ownership: 1,
    description: 'Well-maintained Audi A4 Premium with full service history. Features include leather seats, sunroof, and advanced driver assistance systems.',
    features: ['Leather Seats', 'Sunroof', 'Cruise Control', 'Parking Sensors', 'Touchscreen Infotainment'],
    availabilityStatus: 'Available',
  },
  {
    name: 'BMW X1 sDrive',
    brand: 'BMW',
    year: 2023,
    price: 3990000,
    mileage: 6800,
    fuel: 'Petrol',
    transmission: 'Automatic',
    type: 'SUV',
    state: 'Maharashtra',
    city: 'Pune',
    image: `${BASE_URL}/BMW X1 sDrive.webp`,
    featured: true,
    color: 'Alpine White',
    engine: '1.5L TwinPower Turbo',
    seats: 5,
    ownership: 1,
    description: 'Almost new BMW X1 with barely driven kilometers. Premium features and BMW Connected Drive included.',
    features: ['Panoramic Sunroof', 'BMW iDrive', 'Wireless Charging', 'LED Headlights', 'Sport Mode'],
    availabilityStatus: 'Available',
  },
  {
    name: 'Honda City ZX CVT',
    brand: 'Honda',
    year: 2024,
    price: 1400000,
    mileage: 4100,
    fuel: 'Petrol',
    transmission: 'Automatic',
    type: 'Sedan',
    state: 'Gujarat',
    city: 'Ahmedabad',
    image: `${BASE_URL}/Honda City ZX CVT.webp`,
    featured: false,
    badge: 'Premium',
    color: 'Platinum White Pearl',
    engine: '1.5L i-VTEC',
    seats: 5,
    ownership: 1,
    description: 'Top-of-the-line Honda City ZX with CVT transmission. Loaded with features and extremely fuel efficient.',
    features: ['Honda SENSING', 'Sunroof', 'LED DRLs', 'Wireless Apple CarPlay', 'Lane Watch Camera'],
    availabilityStatus: 'Available',
  },
  {
    name: 'Hyundai Creta SX',
    brand: 'Hyundai',
    year: 2023,
    price: 1250000,
    mileage: 9800,
    fuel: 'Diesel',
    transmission: 'Manual',
    type: 'SUV',
    state: 'Uttar Pradesh',
    city: 'Noida',
    image: `${BASE_URL}/Hyundai Creta SX.jpg`,
    featured: true,
    color: 'Titan Grey',
    engine: '1.5L CRDi',
    seats: 5,
    ownership: 1,
    description: 'Popular Hyundai Creta SX in diesel variant. Excellent mileage and loaded with tech features.',
    features: ['Panoramic Sunroof', 'Ventilated Seats', 'BlueLink Connected', 'ADAS', '10.25" Touchscreen'],
    availabilityStatus: 'Available',
  },
  {
    name: 'Hyundai Venue SX',
    brand: 'Hyundai',
    year: 2024,
    price: 940000,
    mileage: 3600,
    fuel: 'Petrol',
    transmission: 'Automatic',
    type: 'SUV',
    state: 'Rajasthan',
    city: 'Udaipur',
    image: `${BASE_URL}/Hyundai Venue SX.webp`,
    featured: false,
    color: 'Denim Blue',
    engine: '1.0L Turbo GDi',
    seats: 5,
    ownership: 1,
    description: 'Compact SUV with turbo engine. Great for city driving with excellent features in its segment.',
    features: ['Sunroof', 'Wireless Charging', 'BlueLink', 'Air Purifier', 'Rear Camera'],
    availabilityStatus: 'Available',
  },
  {
    name: 'Hyundai i20 Sportz',
    brand: 'Hyundai',
    year: 2023,
    price: 850000,
    mileage: 12400,
    fuel: 'Petrol',
    transmission: 'Manual',
    type: 'Hatchback',
    state: 'Delhi',
    city: 'New Delhi',
    image: `${BASE_URL}/Hyundai i20 Sportz.webp`,
    featured: true,
    color: 'Fiery Red',
    engine: '1.2L Kappa',
    seats: 5,
    ownership: 1,
    description: 'Stylish premium hatchback with great features. Well maintained with full service history.',
    features: ['Touchscreen', 'Rear Parking Sensors', 'Projector Headlamps', 'Steering Controls', 'Bluetooth'],
    availabilityStatus: 'Available',
  },
  {
    name: 'Jeep Compass Limited',
    brand: 'Jeep',
    year: 2022,
    price: 2450000,
    mileage: 9800,
    fuel: 'Petrol',
    transmission: 'Automatic',
    type: 'SUV',
    state: 'Haryana',
    city: 'Gurgaon',
    image: `${BASE_URL}/Jeep Compass Limited.webp`,
    featured: false,
    color: 'Minimal Grey',
    engine: '1.4L MultiAir Turbo',
    seats: 5,
    ownership: 1,
    description: 'Iconic Jeep Compass in Limited trim. Built for adventure with premium interiors.',
    features: ['Panoramic Sunroof', 'UConnect System', 'Leather Seats', '4x2', 'Keyless Entry'],
    availabilityStatus: 'Available',
  },
  {
    name: 'Kia Seltos HTK',
    brand: 'Kia',
    year: 2024,
    price: 1150000,
    mileage: 5200,
    fuel: 'Petrol',
    transmission: 'Automatic',
    type: 'SUV',
    state: 'Maharashtra',
    city: 'Mumbai',
    image: `${BASE_URL}/Kia Seltos HTK.webp`,
    featured: true,
    badge: 'Popular',
    color: 'Glacier White Pearl',
    engine: '1.5L Smartstream',
    seats: 5,
    ownership: 1,
    description: 'Feature-rich Kia Seltos with connected car tech. Excellent build quality and comfort.',
    features: ['UVO Connected', '10.25" Display', 'Bose Sound System', 'Ventilated Seats', 'ADAS Level 2'],
    availabilityStatus: 'Available',
  },
  {
    name: 'Lexus RX 350',
    brand: 'Lexus',
    year: 2024,
    price: 5290000,
    mileage: 3800,
    fuel: 'Petrol',
    transmission: 'Automatic',
    type: 'SUV',
    state: 'West Bengal',
    city: 'Kolkata',
    image: `${BASE_URL}/Lexus RX 350,webp.jpg`,
    featured: false,
    color: 'Sonic Chrome',
    engine: '2.4L Turbo',
    seats: 5,
    ownership: 1,
    description: 'Luxury SUV from Lexus with unmatched refinement and comfort. Virtually new condition.',
    features: ['Mark Levinson Audio', 'Heads-Up Display', 'Air Suspension', 'Panoramic Roof', '14" Touchscreen'],
    availabilityStatus: 'Available',
  },
  {
    name: 'MG Hector Plus Sharp',
    brand: 'MG',
    year: 2024,
    price: 1390000,
    mileage: 4500,
    fuel: 'Petrol',
    transmission: 'Automatic',
    type: 'SUV',
    state: 'Telangana',
    city: 'Hyderabad',
    image: `${BASE_URL}/MG Hector Plus Sharp.webp`,
    featured: true,
    color: 'Starry Black',
    engine: '1.5L Turbo',
    seats: 7,
    ownership: 1,
    description: 'Internet car with 7-seater configuration. Loaded with tech and spacious interiors.',
    features: ['i-SMART Connected', '14" HD Screen', 'Panoramic Sunroof', 'Infinity Sound', 'ADAS'],
    availabilityStatus: 'Available',
  },
  {
    name: 'Mahindra Scorpio N Z8',
    brand: 'Mahindra',
    year: 2023,
    price: 1600000,
    mileage: 8900,
    fuel: 'Diesel',
    transmission: 'Manual',
    type: 'SUV',
    state: 'Maharashtra',
    city: 'Pune',
    image: `${BASE_URL}/Mahindra Scorpio N Z8.webp`,
    featured: true,
    color: 'Deep Forest',
    engine: '2.2L mHawk',
    seats: 7,
    ownership: 1,
    description: 'Powerful body-on-frame SUV with commanding road presence. Built tough for Indian roads.',
    features: ['AdrenoX Connected', 'Sony 3D Sound', 'Sunroof', 'Terrain Modes', 'Cruise Control'],
    availabilityStatus: 'Available',
  },
  {
    name: 'Maruti Suzuki Brezza VXi',
    brand: 'Maruti Suzuki',
    year: 2024,
    price: 950000,
    mileage: 4500,
    fuel: 'Petrol',
    transmission: 'Manual',
    type: 'SUV',
    state: 'Tamil Nadu',
    city: 'Chennai',
    image: `${BASE_URL}/Maruti Suzuki Brezza VXi.webp`,
    featured: true,
    badge: 'Best Value',
    color: 'Sizzling Red',
    engine: '1.5L K-Series',
    seats: 5,
    ownership: 1,
    description: 'India\'s most trusted sub-4m SUV. Excellent resale value and low maintenance costs.',
    features: ['SmartPlay Pro', 'Suzuki Connect', 'HUD', 'Sunroof', 'Rear AC Vents'],
    availabilityStatus: 'Available',
  },
  {
    name: 'Maruti Suzuki Swift VXi',
    brand: 'Maruti Suzuki',
    year: 2024,
    price: 650000,
    mileage: 5200,
    fuel: 'Petrol',
    transmission: 'Manual',
    type: 'Hatchback',
    state: 'Maharashtra',
    city: 'Mumbai',
    image: `${BASE_URL}/Maruti Suzuki Swift VXi.webp`,
    featured: true,
    badge: 'Best Value',
    color: 'Pearl Metallic Lucent Orange',
    engine: '1.2L Z-Series',
    seats: 5,
    ownership: 1,
    description: 'All-new Swift with modern design and excellent fuel efficiency. Perfect city car.',
    features: ['9" SmartPlay', 'Wireless CarPlay', 'Cruise Control', 'Auto Climate Control', 'Push Start'],
    availabilityStatus: 'Available',
  },
  {
    name: 'Nissan Kicks XV',
    brand: 'Nissan',
    year: 2023,
    price: 1080000,
    mileage: 8400,
    fuel: 'Petrol',
    transmission: 'Manual',
    type: 'SUV',
    state: 'Karnataka',
    city: 'Mysore',
    image: `${BASE_URL}/Nissan Kicks XV.webp`,
    featured: false,
    color: 'Pearl White',
    engine: '1.5L HR15DE',
    seats: 5,
    ownership: 1,
    description: 'Underrated compact SUV with great driving dynamics and spacious cabin.',
    features: ['8" Touchscreen', '360° Camera', 'Ambient Lighting', 'Connected Car', 'Auto AC'],
    availabilityStatus: 'Available',
  },
  {
    name: 'Renault Duster RxZ',
    brand: 'Renault',
    year: 2023,
    price: 1060000,
    mileage: 9100,
    fuel: 'Diesel',
    transmission: 'Manual',
    type: 'SUV',
    state: 'Madhya Pradesh',
    city: 'Indore',
    image: `${BASE_URL}/Renault Duster RxZ.webp`,
    featured: false,
    color: 'Caspian Blue',
    engine: '1.5L dCi',
    seats: 5,
    ownership: 1,
    description: 'Rugged and reliable SUV known for its bulletproof diesel engine and excellent ground clearance.',
    features: ['MediaNav', 'Wireless Charging', 'Projector Headlamps', 'Hill Assist', 'ESP'],
    availabilityStatus: 'Available',
  },
  {
    name: 'Tata Altroz XZ',
    brand: 'Tata',
    year: 2024,
    price: 780000,
    mileage: 2300,
    fuel: 'Petrol',
    transmission: 'Manual',
    type: 'Hatchback',
    state: 'Uttar Pradesh',
    city: 'Lucknow',
    image: `${BASE_URL}/Tata Altroz XZ.webp`,
    featured: false,
    color: 'High Street Gold',
    engine: '1.2L Revotron',
    seats: 5,
    ownership: 1,
    description: '5-star GNCAP rated premium hatchback with excellent build quality and safety features.',
    features: ['iRA Connected', '7" Touchscreen', 'Projector Headlamps', 'Rear Disc Brakes', 'Auto AC'],
    availabilityStatus: 'Available',
  },
  {
    name: 'Tata Nexon XZ+',
    brand: 'Tata',
    year: 2024,
    price: 1000000,
    mileage: 3100,
    fuel: 'Petrol',
    transmission: 'Manual',
    type: 'SUV',
    state: 'Karnataka',
    city: 'Bangalore',
    image: `${BASE_URL}/Tata Nexon XZ+.webp`,
    featured: true,
    badge: 'Hot Deal',
    color: 'Fearless Purple',
    engine: '1.2L Turbo Revotron',
    seats: 5,
    ownership: 1,
    description: 'India\'s safest sub-4m SUV with 5-star GNCAP rating. Excellent features at great value.',
    features: ['iRA Connected', 'Ventilated Seats', 'Sunroof', 'Air Purifier', '360° Camera'],
    availabilityStatus: 'Available',
  },
  {
    name: 'Toyota Fortuner 4x4',
    brand: 'Toyota',
    year: 2023,
    price: 3500000,
    mileage: 15600,
    fuel: 'Diesel',
    transmission: 'Automatic',
    type: 'SUV',
    state: 'Rajasthan',
    city: 'Jaipur',
    image: `${BASE_URL}/Toyota Fortuner 4x4.webp`,
    featured: false,
    color: 'Phantom Brown',
    engine: '2.8L GD',
    seats: 7,
    ownership: 1,
    description: 'The king of SUVs. Toyota Fortuner with 4x4 capability and legendary reliability.',
    features: ['4WD', 'Connected Car', 'JBL Sound System', 'Cooled Seats', 'Terrain Select'],
    availabilityStatus: 'Available',
  },
  {
    name: 'Volkswagen Golf GTI',
    brand: 'Volkswagen',
    year: 2023,
    price: 3600000,
    mileage: 11200,
    fuel: 'Petrol',
    transmission: 'Automatic',
    type: 'Hatchback',
    state: 'Rajasthan',
    city: 'Jaipur',
    image: `${BASE_URL}/Volkswagen Golf GTI.webp`,
    featured: false,
    color: 'Kings Red Metallic',
    engine: '2.0L TSI',
    seats: 5,
    ownership: 1,
    description: 'The iconic hot hatchback. Pure driving pleasure with DSG transmission and sport-tuned suspension.',
    features: ['Digital Cockpit Pro', 'DCC Adaptive Suspension', 'Harman Kardon', 'Sport Seats', 'GTI Diff Lock'],
    availabilityStatus: 'Available',
  },
  {
    name: 'Ford Mustang GT',
    brand: 'Ford',
    year: 2022,
    price: 4200000,
    mileage: 9800,
    fuel: 'Petrol',
    transmission: 'Automatic',
    type: 'Coupe',
    state: 'Gujarat',
    city: 'Vadodara',
    image: `${BASE_URL}/ford mustang gt.webp`,
    featured: true,
    color: 'Grabber Blue',
    engine: '5.0L V8',
    seats: 4,
    ownership: 1,
    description: 'American muscle icon. 450+ HP V8 with that unmistakable exhaust note. Head-turner guaranteed.',
    features: ['V8 Engine', 'SYNC 3', 'Recaro Seats', 'Launch Control', 'MagneRide Suspension'],
    availabilityStatus: 'Available',
  },
  {
    name: 'Honda CR-V',
    brand: 'Honda',
    year: 2024,
    price: 3200000,
    mileage: 6200,
    fuel: 'Hybrid',
    transmission: 'Automatic',
    type: 'SUV',
    state: 'Kerala',
    city: 'Kochi',
    image: `${BASE_URL}/honda cr-v.avif`,
    featured: false,
    color: 'Crystal Black Pearl',
    engine: '2.0L e:HEV',
    seats: 5,
    ownership: 1,
    description: 'Hybrid luxury SUV with exceptional fuel efficiency and Honda\'s proven reliability.',
    features: ['Honda SENSING', 'e:HEV Hybrid', 'Hands-Free Tailgate', 'Wireless CarPlay', 'Panoramic Roof'],
    availabilityStatus: 'Available',
  },
];

const seedTestimonials = [
  {
    name: 'Aarav Mehta',
    role: 'BMW X1 Owner',
    image: `${CLIENTS_BASE_URL}/man1.png`,
    text: 'The team at Avni’s Cars Collections made buying my dream car effortless. Transparent pricing, no hidden fees, and they delivered it to my doorstep.',
    rating: 5,
    carPurchased: 'BMW X1 sDrive',
    isVisible: true,
  },
  {
    name: 'Sneha Sharma',
    role: 'Hyundai Creta Owner',
    image: `${CLIENTS_BASE_URL}/woman1.png`,
    text: 'I traded in my old sedan and got a fantastic deal on a pre-owned Creta. The financing options were better than any bank offered me.',
    rating: 5,
    carPurchased: 'Hyundai Creta SX',
    isVisible: true,
  },
  {
    name: 'Rohan Gupta',
    role: 'Toyota Fortuner Owner',
    image: `${CLIENTS_BASE_URL}/man2.png`,
    text: 'As a car enthusiast, I appreciate their curated selection. Every vehicle is genuinely well-maintained — you can tell they care about quality.',
    rating: 5,
    carPurchased: 'Toyota Fortuner 4x4',
    isVisible: true,
  },
  {
    name: 'Ananya Iyer',
    role: 'Kia Seltos Owner',
    image: `${CLIENTS_BASE_URL}/woman2.png`,
    text: 'From browsing online to signing the papers, the entire process was seamless. Absolutely the best dealership experience I’ve ever had.',
    rating: 5,
    carPurchased: 'Kia Seltos HTK',
    isVisible: true,
  },
  {
    name: 'Vikram Malhotra',
    role: 'Audi A4 Owner',
    image: `${CLIENTS_BASE_URL}/man1.png`,
    text: 'Excellent service and complete transparency. They gave me a great trade-in value and the Audi A4 was in pristine, showroom condition.',
    rating: 5,
    carPurchased: 'Audi A4 Premium',
    isVisible: true,
  },
  {
    name: 'Anisha Kapoor',
    role: 'Lexus RX 350 Owner',
    image: `${CLIENTS_BASE_URL}/woman1.png`,
    text: 'The staff is highly professional. The White-Glove service is real—they handled all the paperwork and delivered the car to my office.',
    rating: 5,
    carPurchased: 'Lexus RX 350',
    isVisible: true,
  },
  {
    name: 'Rajesh Sharma',
    role: 'Tata Nexon Owner',
    image: `${CLIENTS_BASE_URL}/man2.png`,
    text: 'Avni’s Cars Collections completely changed my perception of buying a pre-owned car. The transparency and luxury service were unmatched.',
    rating: 5,
    carPurchased: 'Tata Nexon XZ+',
    isVisible: true,
  },
  {
    name: 'Priya Desai',
    role: 'MG Hector Owner',
    image: `${CLIENTS_BASE_URL}/woman2.png`,
    text: 'I found my dream SUV here. The team was incredibly knowledgeable and never pushy. Truly a white-glove experience.',
    rating: 5,
    carPurchased: 'MG Hector Plus Sharp',
    isVisible: true,
  },
  {
    name: 'Vikram Mehta',
    role: 'Mahindra Scorpio N Owner',
    image: `${CLIENTS_BASE_URL}/man1.png`,
    text: 'From the test drive to the financing, everything was seamless. I highly recommend Avni for anyone looking for premium quality.',
    rating: 5,
    carPurchased: 'Mahindra Scorpio N Z8',
    isVisible: true,
  }
];

const seedOffers = [
  {
    title: 'Up to ₹50,000 Exchange Bonus',
    description: 'Upgrade to a premium vehicle effortlessly. Trade in your old car and receive an exclusive bonus applied directly to your purchase.',
    discountPercentage: 10,
    validityDate: new Date(new Date().getFullYear(), new Date().getMonth() + 1, new Date().getDate()), // 1 month from now
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=600&q=80',
    ctaText: 'Explore',
    active: true,
  },
  {
    title: 'Zero Downpayment Drive',
    description: 'Take home your dream car today with 100% financing options available. Fast approvals, competitive interest rates, and customized EMI plans.',
    discountPercentage: null,
    validityDate: new Date(new Date().getFullYear(), new Date().getMonth() + 2, new Date().getDate()), // 2 months from now
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=600&q=80',
    ctaText: 'Calculate EMI',
    active: true,
  },
  {
    title: 'Complimentary Care Package',
    description: 'Drive with absolute peace of mind. All certified pre-owned vehicles purchased this month include 1-year free insurance and extended warranty.',
    discountPercentage: null,
    validityDate: new Date(new Date().getFullYear(), new Date().getMonth() + 1, new Date().getDate()), // 1 month from now
    image: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=600&q=80',
    ctaText: 'Contact Sales',
    active: true,
  }
];

async function seed() {
  try {
    await sequelize.authenticate();
    console.log('✓ Database connected');

    console.log('✓ Clearing existing database records...');
    await Car.destroy({ where: {}, truncate: false });
    await GalleryItem.destroy({ where: {}, truncate: false });
    await Testimonial.destroy({ where: {}, truncate: false });
    await SpecialOffer.destroy({ where: {}, truncate: false });

    // Bulk create all cars (set to everywhere since they have corresponding gallery items)
    const carsToSeed = cars.map(c => ({ ...c, placement: 'everywhere' }));
    const created = await Car.bulkCreate(carsToSeed);
    console.log(`✓ Successfully seeded ${created.length} cars into the database`);

    // Bulk create gallery items matching the cars
    const galleryItems = created.map((car, idx) => ({
      url: car.image,
      image_url: car.image,
      caption: car.name,
      category: car.brand,
      orderIndex: idx,
      carId: String(car.id),
    }));
    const createdGallery = await GalleryItem.bulkCreate(galleryItems);
    console.log(`✓ Successfully seeded ${createdGallery.length} gallery items into the database`);

    // Bulk create testimonials
    const createdTestimonials = await Testimonial.bulkCreate(seedTestimonials);
    console.log(`✓ Successfully seeded ${createdTestimonials.length} testimonials into the database`);

    // Bulk create special offers
    const createdOffers = await SpecialOffer.bulkCreate(seedOffers);
    console.log(`✓ Successfully seeded ${createdOffers.length} special offers into the database`);

    // Seed default admin if not existing
    const adminExists = await Admin.findOne({ where: { email: 'adminavnicarscollections@gmail.com' } });
    if (!adminExists) {
      await Admin.create({
        name: 'Avni’s Cars Collections Admin',
        email: 'adminavnicarscollections@gmail.com',
        password: 'avniauto1234',
      });
      console.log('✓ Successfully seeded default Admin user');
    } else {
      console.log('✓ Admin user already exists');
    }

    process.exit(0);
  } catch (error) {
    console.error('✗ Seed failed:', error);
    process.exit(1);
  }
}

seed();
